### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by tmoflash** [SilverCory/SpongePls#17]
I am getting the error:

'Could not connect ot a default or fallback server, please try again later: io.netty.channel-AbstractChannel$AnnotatedConnectionException.

Forge Version: forge-1.12.2-14.23.4.2705-universal.jar
SpongeForge Version: spongeforge-1.12.2-2705-7.1.0-BETA-3136.jar
BungeeCord Version: Last build (#1318)
SpongPLS Version: latest build - this is what I have in the config (no idea if it is correct)
**allowed-servers:
  - '.*'
  - 'hub'
  - '(.*nomatch.*)'
  - 'CaseInsensaTiVe'**

I have set ip forward and bungeecord to: true w/in bc config and also on sponge/global.conf

Currently hub is the only server and I cannot connect.

**Comment by SilverCory** [comment]
I take it by the fact you closed this it was fixed @tmoflash, what was the issue and how did you fix it?

**Comment by RhvsW** [comment]
kappapride

**Comment by tmoflash** [comment]
I have not resolved. I do not think it is your plugin. Didn't want to spin
your wheels. I switched to waterfall, I think it is a broken build
somewhere. Trying to do trial and error to pinpoint.

**Comment by SilverCory** [comment]
@tmoflash it might be the plugin, there's another one I can't remember what but it's a lot more supported I suggest you try that if you're using sponge and bungee, the link is on the original spongepowered.org thread.

**Comment by tmoflash** [comment]
I used the other plugin and put in the latest bungeecord build. It is like it isn't even talking. I run BC commands in the hub site and nothing works. Either I screwed something up in the config (which is possible, but have gone over 100 times). Or there is a broken build somewhere.

**Comment by SilverCory** [comment]
I've not kept up with Minecraft as a whole sorry I can't help :')
